config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :debates do
    resources :comments
  end

  root "debates#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :debate, foreign_key: "debate_id"
end

app/models/debate.rb
class Debate < ApplicationRecord
  has_many :comments, dependent: :destroy

  validates :title, presence: true, length: { minimum: 3, message: "議題が短すぎます。" }
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @debate = Debate.find(params[:debate_id])
    @debate.comments.create(comment_params)
    redirect_to debate_path(@debate)
  end

  private
    def comment_params
      params.require(:comment).permit(:name, :age, :profession, :message)
    end
end

app/controllers/debates_controller.rb
class DebatesController < ApplicationController

  def index
    @debates = Debate.all.order(created_at: "desc")
  end

  def show
    @debate = Debate.find(params[:id])
    @comments = @debate.comments.all.order(created_at: "desc")
  end

  def new
    @debate = Debate.new
  end

  def create
    @debate = Debate.new(debate_params)
    if @debate.save
      redirect_to debates_path
    else
      render "new"
    end
  end

  def edit
    @debate = Debate.find(params[:id])
  end

  def update
    @debate = Debate.find(params[:id])
    if @debate.update(debate_params)
      redirect_to debates_path
    else
      render "edit"
    end
  end

  def destroy
    @debate = Debate.find(params[:id])
    @debate.destroy
    redirect_to debates_path
  end

  private
    def debate_params
      params.require(:debate).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/debates_helper.rb
module DebatesHelper
end

app/views/debates/edit.html.erb
<div class="new-debate">
  <h2>Edit Debate</h2>
  <p>議題を編集してください。</p>

  <%= form_for @debate, url: debate_path(@debate) do |f| %>
  <ul>
    <li>
      <%= f.text_field :title, placeholder: "ここに議題を入力してください。" %>
      <% if @debate.errors.messages[:title].any? %>
      <p class="error-new-debate"><%= @debate.errors.messages[:title][0] %></p>
      <% end %>
    </li>
    <li>
      <%= f.text_area :body, placeholder: "ここに議題の詳細を入力してください。" %>
      <% if @debate.errors.messages[:body].any? %>
      <p class="error-new-debate"><%= @debate.errors.messages[:body][0] %></p>
      <% end %>
    </li>
    <li>
      <%= f.submit "編集確定"%>
    </li>
  </ul>
  <% end %>
</div>

app/views/debates/index.html.erb
<div class="index-debate">
  <ul>
    <% @debates.each do |debate| %>
    <li>
      <h3>議題：<%= link_to debate.title, debate_path(debate) %></h3>
      <p>詳細：<%= debate.body %></p>
      <div class="update-form">
        <%= link_to "[削除]", 
          debate_path(debate),
          method: :delete,
          class: "delete-debate",
          data: { confirm: "削除しますか？" } %>
        <%= link_to "[編集]", edit_debate_path(debate), class: "edit-debate" %>
      </div>
    </li>
    <% end %>
  </ul>
</div>

app/views/debates/new.html.erb
<div class="new-debate">
  <h2>Add New Debate</h2>
  <p>新規議題を作成してください。</p>

  <%= form_for :post, url: debates_path do |f| %>
  <ul>
    <li>
      <%= f.text_field :title, placeholder: "ここに議題を入力してください。" %>
      <% if @debate.errors.messages[:title].any? %>
      <p class="error-new-debate"><%= @debate.errors.messages[:title][0] %></p>
      <% end %>
    </li>
    <li>
      <%= f.text_area :body, placeholder: "ここに議題の詳細を入力してください。" %>
      <% if @debate.errors.messages[:body].any? %>
      <p class="error-new-debate"><%= @debate.errors.messages[:body][0] %></p>
      <% end %>
    </li>
    <li>
      <%= f.submit "新規議題作成"%>
    </li>
  </ul>
  <% end %>
</div>

app/views/debates/show.html.erb
<div class="debate-title">
  <h1><span>議題:</span><%= @debate.title %></h1>
  <p><%= @debate.body %></p>
</div>

<%= form_for([@debate, @debate.comments.build]) do |f| %>
  <ul class="comment-create-form">
    <li class="comment-form-name">
      <%= f.text_field :name, placeholder: "名前" %>
    </li>
    <li class="comment-form-age">
      <%= f.number_field :age, placeholder: "年齢" %>
    </li>
    <li  class="comment-form-profession">
      <%= f.text_field :profession, placeholder: "職業" %>
    </li>
    <li  class="comment-form-message">
      <%= f.text_field :message, placeholder: "コメントを入力してください。" %>
    </li>
    <li  class="comment-form-submit">
      <%= f.submit "送信"%>
    </li>
  </ul>
<% end %>

<ul>
  <% @comments.each do |comment| %>
  <li class="comment-contents">
    <div class="comment-profile">
      <p>名前:<span><%= comment.name %></span></p>
      <p>年齢:<span><%= comment.age %></span></p>
      <p>職業:<span><%= comment.profession %></span></p>
      <p>送信日時:<span><%= comment.created_at.strftime("%Y年%m月%d日 %H:%M") %></span></p>
    </div>
    <h3><%= comment.message %><h3>
  </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DebateApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="top-menu">
      <ul>
        <li class="title"><%= link_to "DebateApp", debates_path %></li>
        <li><%= link_to "新規議題作成", new_debate_path %></li>
      </ul>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>